- name: Add Newrelic's APT Repository
  apt_repository: repo='deb http://apt.newrelic.com/debian/ newrelic non-free' state=present

- name: Add Newrelic's APT key
  apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present

- name: Install Newrelic's sysmond Agent
  apt: name=newrelic-sysmond state=present update_cache=yes
